import { X, Printer, Download, FileText, CheckCircle2, AlertTriangle, ShieldCheck, HardHat, Truck, Mail } from 'lucide-react'
import { useToastStore } from '@/store/useToastStore'

interface DailySiteReportModalProps {
  isOpen: boolean
  onClose: () => void
}

export function DailySiteReportModal({ isOpen, onClose }: DailySiteReportModalProps) {
  const { addToast } = useToastStore()
  if (!isOpen) return null

  const handlePrint = () => {
    window.print()
  }

  const handleSendEmail = () => {
    const email = localStorage.getItem('alert_notification_email') || 'security@devavision.ai'
    addToast({
      title: 'Report Email Sent',
      message: `Daily Site Safety & Operations summary has been dispatched to ${email}`,
      type: 'success',
    })
  }

  const todayStr = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-md animate-fadeIn">
      <div className="bg-background border border-foreground/15 rounded-3xl w-full max-w-3xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden print:max-w-none print:w-full print:h-full print:rounded-none print:border-none">
        
        {/* Modal Header */}
        <div className="p-6 border-b border-foreground/10 flex justify-between items-center bg-foreground/5 shrink-0 print:hidden">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-primary/15 text-primary border border-primary/20">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-foreground">Daily Site Safety & Operations Report</h2>
              <p className="text-xs text-muted-foreground">Generated by AI CCTV Analytics • {todayStr}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleSendEmail}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-accent hover:bg-accent/90 text-white text-xs font-bold transition-all shadow-md"
            >
              <Mail className="w-4 h-4" /> Send to Email
            </button>
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-primary hover:bg-primary/90 text-white text-xs font-bold transition-all shadow-md"
            >
              <Printer className="w-4 h-4" /> Print / Export PDF
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-xl text-muted-foreground hover:text-foreground hover:bg-foreground/10 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Content Body */}
        <div className="p-6 overflow-y-auto space-y-6 flex-1 text-sm custom-scrollbar print:p-0 print:overflow-visible">
          
          {/* Header section (Visible in print) */}
          <div className="hidden print:block mb-6 border-b pb-4">
            <h1 className="text-2xl font-bold text-black">DEVA VISION AI — DAILY CONSTRUCTION REPORT</h1>
            <p className="text-sm text-gray-600">Site: Hero Homes NCR • Date: {todayStr}</p>
          </div>

          {/* Executive Summary Card */}
          <div className="p-4 rounded-2xl bg-success/10 border border-success/20 flex justify-between items-center">
            <div className="flex items-center gap-3">
              <ShieldCheck className="w-8 h-8 text-success shrink-0" />
              <div>
                <h4 className="font-bold text-foreground">Overall Safety Index: 96.4% (EXCELLENT)</h4>
                <p className="text-xs text-muted-foreground mt-0.5">0 critical injuries, 2 minor helmet warnings issued & acknowledged.</p>
              </div>
            </div>
            <span className="px-3 py-1 rounded-full text-xs font-bold bg-success text-white">PASSED</span>
          </div>

          {/* 3 Metric Summary Boxes */}
          <div className="grid grid-cols-3 gap-4">
            <div className="p-4 rounded-2xl bg-foreground/5 border border-foreground/10 flex flex-col gap-1">
              <span className="text-xs text-muted-foreground flex items-center gap-1 font-semibold">
                <HardHat className="w-4 h-4 text-primary" /> Manpower On Site
              </span>
              <span className="text-2xl font-extrabold text-foreground">54 Workers</span>
              <span className="text-[11px] text-success">38 General, 12 Staff, 4 Visitors</span>
            </div>
            <div className="p-4 rounded-2xl bg-foreground/5 border border-foreground/10 flex flex-col gap-1">
              <span className="text-xs text-muted-foreground flex items-center gap-1 font-semibold">
                <AlertTriangle className="w-4 h-4 text-warning" /> Safety Violations
              </span>
              <span className="text-2xl font-extrabold text-foreground">2 Incidents</span>
              <span className="text-[11px] text-warning">2 PPE Helmet Missing (Resolved)</span>
            </div>
            <div className="p-4 rounded-2xl bg-foreground/5 border border-foreground/10 flex flex-col gap-1">
              <span className="text-xs text-muted-foreground flex items-center gap-1 font-semibold">
                <Truck className="w-4 h-4 text-info" /> Material Trucks
              </span>
              <span className="text-2xl font-extrabold text-foreground">8 Trucks</span>
              <span className="text-[11px] text-info">2 Cement, 4 Steel, 2 Aggregate</span>
            </div>
          </div>

          {/* Safety & PPE Breach Log */}
          <div>
            <h3 className="font-bold text-foreground text-sm uppercase tracking-wider mb-3">Today's Safety & AI Detections Log</h3>
            <div className="border border-foreground/10 rounded-2xl overflow-hidden">
              <table className="w-full text-left text-xs">
                <thead className="bg-foreground/5 text-muted-foreground border-b border-foreground/10 font-bold uppercase tracking-wider">
                  <tr>
                    <th className="p-3">Time</th>
                    <th className="p-3">Camera</th>
                    <th className="p-3">Violation / Event</th>
                    <th className="p-3">Risk Level</th>
                    <th className="p-3">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-foreground/10">
                  <tr>
                    <td className="p-3 font-medium">09:14 AM</td>
                    <td className="p-3 text-muted-foreground">CAM-02 Tower A Ground</td>
                    <td className="p-3 font-bold text-foreground">Missing Helmet Detection</td>
                    <td className="p-3"><span className="px-2 py-0.5 rounded bg-warning/20 text-warning font-bold">WARNING</span></td>
                    <td className="p-3 text-success font-bold flex items-center gap-1"><CheckCircle2 className="w-3.5 h-3.5" /> Resolved</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-medium">11:42 AM</td>
                    <td className="p-3 text-muted-foreground">CAM-04 Gate 1 ANPR</td>
                    <td className="p-3 font-bold text-foreground">Material Truck Dispatched</td>
                    <td className="p-3"><span className="px-2 py-0.5 rounded bg-info/20 text-info font-bold">INFO</span></td>
                    <td className="p-3 text-muted-foreground font-semibold">Log Recorded</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-medium">02:30 PM</td>
                    <td className="p-3 text-muted-foreground">CAM-01 Crane View</td>
                    <td className="p-3 font-bold text-foreground">Restricted Zone Entry</td>
                    <td className="p-3"><span className="px-2 py-0.5 rounded bg-danger/20 text-danger font-bold">CRITICAL</span></td>
                    <td className="p-3 text-success font-bold flex items-center gap-1"><CheckCircle2 className="w-3.5 h-3.5" /> Acknowledged</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* AI Auditor Sign-off */}
          <div className="p-4 rounded-2xl bg-foreground/5 border border-foreground/10 flex justify-between items-center text-xs text-muted-foreground">
            <div>
              <p className="font-semibold text-foreground">DevaVision AI Engine v2.4 Automated Audit</p>
              <p>Continuous 24/7 Monitoring • Cryptographically Verified Log</p>
            </div>
            <div className="text-right">
              <p className="font-bold text-foreground">Authorized Site Supervisor</p>
              <p className="italic">Sign-off: _____________________</p>
            </div>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="p-4 border-t border-foreground/10 bg-foreground/5 flex justify-end gap-2 shrink-0 print:hidden">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-foreground/10 hover:bg-foreground/20 text-foreground text-xs font-bold transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  )
}
